name: 'Build & Publish'

on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: installer-linux.zip
            commands: |
              mkdir -p installer/utility
              mv target/release/aiosaber-client installer/
              mv install/utility/serviceman-linux installer/utility/
              mv install/linux-* installer/
              zip -r installer.zip installer/*
          - os: windows-latest
            asset_name: installer-win.zip
            commands: |
              mkdir installer\utility
              move target\release\aiosaber-client.exe installer\
              move install\utility\serviceman-win.exe installer\utility\
              move install\windows-* installer\
              tar -c -a -f installer.zip installer\*
          - os: macos-latest
            asset_name: installer-mac.zip
            commands: |
              mkdir -p installer/utility
              mv target/release/aiosaber-client installer/
              mv install/utility/serviceman-mac installer/utility/
              mv install/mac-* installer/
              zip -r installer.zip installer/*

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: cargo build --locked
      - name: Create installer.zip
        run: ${{ matrix.commands }}
      - name: Provide archives for testing
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: installer.zip
